---
baseurl: https://larry-price.com/
languageCode: en-us
title: Larry Price
subtitle: And the Endless Cup of Coffee
taxonomies:
    tag: tags
permalinks:
    _posts: /blog/:year/:month/:day/:title/
metadataformat: yaml
pygmentsstyle: tango
---